# networks
actor_configs:
  clip_mean: 1.0
  final_fc_init_scale: 1.0e-4
  hidden_dims: !!python/tuple
  - 1024
  - 1024
  - 1024
  name_activation: tanh
  state_dependent_std: true
  use_layer_norm: true
critic_configs:
  hidden_dims: !!python/tuple
  - 256
  - 256
  - 256
  name_activation: relu
  use_layer_norm: true
# dictionaries
update_coef: true
update_dict: true
dict_configs:
  alpha: 0.001
  c: 1.0
  method: lasso_lars
  positive_code: false
  scale_code: false
# optimizers
pi_opt_configs:
  optim_algo: adam
  clip_method: none
  max_norm: -1
  opt_kargs:
    learning_rate: 3.0e-4
    b1: 0.9
    b2: 0.95
q_opt_configs:
  optim_algo: adamw
  clip_method: none
  max_norm: -1
  opt_kargs:
    learning_rate: 3.0e-4
    b1: 0.9
    b2: 0.95
    weight_decay: 1.0e-5
t_opt_configs:
  optim_algo: adam
  clip_method: none
  max_norm: -1
  opt_kargs:
    learning_rate: 3.0e-4
    b1: 0.9
    b2: 0.95
# SAC misc
init_temperature: 1.0
target_update_period: 1
target_entropy: -4.0
tau: 0.005
