# networks
actor_configs:
  clip_mean: 1.0
  final_fc_init_scale: 0.0001
  hidden_dims: !!python/tuple
  - 1024
  - 1024
  name_activation: relu
  state_dependent_std: true
  use_layer_norm: true
critic_configs:
  hidden_dims: !!python/tuple
  - 256
  - 256
  name_activation: relu
  use_layer_norm: true
# dictionaries
update_coef: true
update_dict: true
dict_configs:
  alpha: 0.001
  c: 1.0
  method: lasso_lars
  positive_code: false
  scale_code: false
# optimizers
pi_opt_configs:
  clip_method: none
  lr: 0.0003
  max_norm: -1
  optim_algo: adam
q_opt_configs:
  clip_method: none
  lr: 0.001
  max_norm: -1
  optim_algo: adam
t_opt_configs:
  clip_method: none
  lr: 0.0003
  max_norm: -1
  optim_algo: adam
# SAC misc
init_temperature: 0.0
target_update_period: 1
target_entropy: -2.0
tau: 0.005
